all:
	rustc add.rs --target=wasm32-unknown-unknown
	rustc passing-data.rs --target=wasm32-unknown-unknown
	rustc host-functions.rs --target=wasm32-unknown-unknown
	rustc handling-errors.rs --target=wasm32-unknown-unknown
	rustc early-exit.rs --target=wasm32-unknown-unknown
